apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: {{cookiecutter.component_id | jsonify}}
  description: {{cookiecutter.description | jsonify}}
  annotations:
    github.com/project-slug: {{cookiecutter.storePath | jsonify}}
    backstage.io/techdocs-ref: github:https://github.com/{{cookiecutter.storePath}}
spec:
  type: mobileapp
  lifecycle: experimental
  owner: {{cookiecutter.owner | jsonify}}